name: tiles
version: 0.2.0+3
author: Jakuub Uhrik <jakuub@mail.com>
description: The UI component library inspirated by Facebook React Javascript library.
homepage: https://github.com/cleandart/tiles
dependencies:
  logging: '>=0.9.1+1 <0.10.0'
dev_dependencies:
  browser: any
  meta: any
  mockito: any
  react: any
  test: any
  useful: any
  webdriver: any
